[workspace]
members = [
        "driver",
        "adapter",
        "app",
        "kernel",
]

[workspace.dependencies]
uuid = { version = "1.3.1", features = ["v4"] }
anyhow = "1.0.70"
serde = { version="1.0.160",features=["derive"] }
tokio = { version = "1.27.0", features = ["full"] }
